version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.6.4-node-browsers
        environment:
          MIX_ENV: test
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: corex_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout

      - run: elixir -v
      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - restore_cache:
          key: v1-build-cache-{{ .Branch }}
      - restore_cache:
          key: v1-yarn-cache-{{ .Branch }}-{{ checksum "assets/yarn.lock" }}

      - run: mix do deps.get, compile
      - run: cd assets && yarn install
      - run: cd assets && yarn deploy
      - run: mix phoenix.digest

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: mix test

      - store_test_results:
          path: _build/results.xml